---
security:

environments:
  dev:
    infrastructure:
      max_nodes: 2
      min_nodes: 0
      desired_nodes: 1

    cluster:
      cluster_name: ia
      cluster_version: "1.33"
      upgrade_policy: STANDARD
      addons:
        - name: coredns
          version: v1.12.1-eksbuild.2
        - name: vpc-cni
          version: v1.19.5-eksbuild.3
        - name: kube-proxy
          version: v1.33.0-eksbuild.2
        - name: aws-ebs-csi-driver
          version: v1.44.0-eksbuild.1
        - name: aws-efs-csi-driver
          version: v2.1.8-eksbuild.1
        - name: aws-mountpoint-s3-csi-driver
          version: v1.14.1-eksbuild.1
        - name: eks-pod-identity-agent
          version: v1.3.7-eksbuild.2
        - name: cert-manager
          version: v1.17.2-eksbuild.1
...
