---
environments:
  dev:
    max_nodes: 2
    min_nodes: 2
    desired_nodes: 2
    cluster_version: "1.32"
    addons_servions:
      coredns:  v1.11.4-eksbuild.2
      vpc-cni:  v1.19.3-eksbuild.1
      kube-proxy: v1.32.0-eksbuild.2
      aws-ebs-csi-driver: v1.40.0-eksbuild.1
      aws-efs-csi-driver: v2.1.6-eksbuild.1
      aws-mountpoint-s3-csi-driver: v1.12.0-eksbuild.1
